# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ CI ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm npm install -g truffle 
# This global installation is not needed actually, we can reference local truffle  ./node_modules/.bin
  ganache-cli:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ganache-cli -s 0 -i 420 -a 30 -l 7000000
  tests:
    needs: ganache-cli
    runs-on: ubuntu-latest
    steps:
      - run: truffle test

